/** Training Kitchen — 18 taste profiles with education metadata */

export const TRAINING_FLAVORS = [
  {
    id: 'umami',
    name: 'Umami-forward',
    tags: ['asian', 'italian'],
    pillars: ['salt', 'ferment', 'glutamate'],
    lesson: 'Umami is the fifth taste — savory depth from soy, parmesan, mushrooms, tomato paste, and slow browning.',
    build: ['Add tomato paste and brown it', 'Finish with parmesan or fish sauce', 'Use dried mushrooms in stocks'],
    balance: 'Pair with acid (lemon, vinegar) so richness does not taste flat or heavy.',
  },
  {
    id: 'bright_acid',
    name: 'Bright & Acidic',
    tags: ['mediterranean', 'vietnamese'],
    pillars: ['acid', 'fresh_herb', 'salt'],
    lesson: 'Acid lifts fat and salt — finish with citrus, vinegar, or pickled elements; never only at the start.',
    build: ['Deglaze with wine or vinegar', 'Add citrus zest at the end', 'Quick-pickle onions for garnish'],
    balance: 'If too sharp, add fat (olive oil, butter) or a touch of sweetness.',
  },
  {
    id: 'rich_creamy',
    name: 'Rich & Creamy',
    tags: ['french', 'comfort'],
    pillars: ['fat', 'salt', 'umami'],
    lesson: 'Cream, butter, and cheese carry flavor — build sauce on a roux or reduced stock first.',
    build: ['Reduce liquid before adding dairy', 'Mount cold butter off heat', 'Use aged cheese sparingly at finish'],
    balance: 'Cut with acid (lemon, white wine) or bitter greens on the plate.',
  },
  {
    id: 'spicy_heat',
    name: 'Spicy Heat',
    tags: ['mexican', 'thai', 'indian'],
    pillars: ['capsaicin', 'fat', 'acid'],
    lesson: 'Heat needs fat to spread and acid to refresh — capsaicin is oil-soluble, not water-soluble.',
    build: ['Bloom chili in hot oil', 'Layer fresh and dried chilies', 'Serve with cooling yogurt or lime'],
    balance: 'Sugar and acid tame burn; dairy fat soothes without killing flavor.',
  },
  {
    id: 'smoky',
    name: 'Smoky',
    tags: ['bbq', 'mexican'],
    pillars: ['smoke', 'salt', 'umami'],
    lesson: 'Smoke from wood, chipotle, paprika, or char — a little goes far; build in layers.',
    build: ['Dry rub with smoked paprika', 'Char peppers over flame', 'Finish with smoked salt'],
    balance: 'Bright acid and fresh herbs keep smoke from tasting one-note.',
  },
  {
    id: 'herbaceous',
    name: 'Herbaceous',
    tags: ['mediterranean', 'italian'],
    pillars: ['fresh_herb', 'olive_oil', 'acid'],
    lesson: 'Soft herbs (basil, cilantro) at the end; hardy herbs (rosemary, thyme) early in cooking.',
    build: ['Chop herbs just before serving', 'Infuse oil with hardy herbs', 'Gremolata or chimichurri finish'],
    balance: 'Salt and acid make herbs pop; too much heat kills delicate aroma.',
  },
  {
    id: 'sweet_savory',
    name: 'Sweet-Savory',
    tags: ['asian', 'american'],
    pillars: ['sweet', 'salt', 'umami'],
    lesson: 'Caramelized onions, maple glaze, teriyaki — sweetness needs salt and acid to taste complex.',
    build: ['Reduce until sticky', 'Add soy or fish sauce for depth', 'Finish with vinegar splash'],
    balance: 'If cloying, add acid; if flat, add salt before more sugar.',
  },
  {
    id: 'earthy',
    name: 'Earthy',
    tags: ['comfort', 'indian'],
    pillars: ['root_veg', 'mushroom', 'warm_spice'],
    lesson: 'Mushrooms, beets, lentils, cumin — depth from roasting and long simmering.',
    build: ['Roast roots until caramelized', 'Deglaze with wine', 'Toast spices in fat before wet ingredients'],
    balance: 'Fresh acid and herbs on top keep earthiness from feeling heavy.',
  },
  {
    id: 'tangy',
    name: 'Tangy',
    tags: ['southern', 'filipino'],
    pillars: ['acid', 'ferment', 'salt'],
    lesson: 'Vinegar, buttermilk, yogurt marinades — tang tenderizes and brightens rich food.',
    build: ['Marinate in acid + salt', 'Pickle vegetables as side', 'Splash vinegar at service'],
    balance: 'Fat rounds sharp tang; sugar only if balance still reads sour.',
  },
  {
    id: 'nutty',
    name: 'Nutty & Toasted',
    tags: ['mediterranean', 'asian'],
    pillars: ['toast', 'fat', 'salt'],
    lesson: 'Toast nuts, seeds, and grains — brown butter and sesame oil are instant nutty depth.',
    build: ['Toast nuts in dry pan', 'Brown butter for finish', 'Use tahini or peanut butter in sauces'],
    balance: 'Acid and fresh crunch (herbs, cucumber) keep nutty richness lively.',
  },
  {
    id: 'fresh_light',
    name: 'Fresh & Light',
    tags: ['vietnamese', 'mediterranean'],
    pillars: ['acid', 'herb', 'texture'],
    lesson: 'Raw crunch, citrus, and minimal fat — season aggressively because there is less fat to carry salt.',
    build: ['Salt vegetables to draw moisture', 'Dress at last minute', 'Use high-quality olive oil sparingly'],
    balance: 'Umami anchor (fish sauce, parmesan) stops "diet food" blandness.',
  },
  {
    id: 'bbq',
    name: 'BBQ Profile',
    tags: ['bbq', 'southern'],
    pillars: ['smoke', 'sweet', 'acid', 'spice'],
    lesson: 'Classic BBQ balance: sweet molasses/brown sugar, vinegar tang, smoke, and pepper heat.',
    build: ['Dry rub under skin', 'Spritz with vinegar during cook', 'Glaze in last 15 minutes'],
    balance: 'Too sweet? More vinegar. Too sharp? Touch of fat or honey.',
  },
  {
    id: 'bitter_bright',
    name: 'Bitter-Bright',
    tags: ['italian', 'mediterranean'],
    pillars: ['bitter_green', 'acid', 'olive_oil'],
    lesson: 'Radicchio, arugula, coffee, dark chocolate in savory — bitterness needs salt and fat.',
    build: ['Char bitter greens lightly', 'Balance with sweet fruit or balsamic', 'Use olive oil generously'],
    balance: 'Sweet and acid turn bitterness into complexity, not harshness.',
  },
  {
    id: 'aromatic_spice',
    name: 'Aromatic Spice',
    tags: ['indian', 'moroccan'],
    pillars: ['whole_spice', 'fat', 'heat'],
    lesson: 'Toast whole spices, bloom ground spices in fat — fat carries volatile aromatics.',
    build: ['Temper spices in hot ghee/oil', 'Layer whole and ground', 'Finish with fresh spice (cardamom, mint)'],
    balance: 'Yogurt, coconut milk, or tomato cools and carries spice evenly.',
  },
  {
    id: 'coastal_brine',
    name: 'Coastal & Briny',
    tags: ['greek', 'spanish'],
    pillars: ['salt', 'seafood', 'acid'],
    lesson: 'Anchovy, capers, olives, seaweed — brine is seasoning; taste before adding more salt.',
    build: ['Dissolve anchovy in warm oil', 'Use pasta water saltiness', 'Finish with lemon not more salt'],
    balance: 'Fresh herbs and olive oil soften brine; starch (bread, potatoes) absorbs intensity.',
  },
  {
    id: 'fermented_depth',
    name: 'Fermented Depth',
    tags: ['korean', 'japanese'],
    pillars: ['ferment', 'umami', 'acid'],
    lesson: 'Miso, kimchi, fish sauce, sourdough — fermentation adds complexity you cannot fake quickly.',
    build: ['Stir miso off boil', 'Use kimchi juice in fried rice', 'Fermented chili pastes in marinades'],
    balance: 'Fresh raw veg and acid keep fermented dishes from feeling one-dimensional.',
  },
  {
    id: 'floral_citrus',
    name: 'Floral & Citrus',
    tags: ['persian', 'thai'],
    pillars: ['citrus', 'floral_herb', 'sweet'],
    lesson: 'Orange blossom, rose, lemongrass, kaffir lime — use sparingly; aroma is not volume.',
    build: ['Zest before juice', 'Infuse cream or syrup', 'Add delicate herbs at service'],
    balance: 'Salt and acid ground floral notes so they taste food, not perfume.',
  },
  {
    id: 'comfort_soul',
    name: 'Comfort & Soul',
    tags: ['soul_food', 'comfort'],
    pillars: ['fat', 'salt', 'slow_cook', 'spice'],
    lesson: 'Low and slow, well-seasoned layers — soul food depth comes from time, fond, and spice blend.',
    build: ['Season every layer', 'Use smoked meat for base', 'Finish with hot sauce or vinegar table-side'],
    balance: 'Pickled or fresh sides cut richness; acid at the table lets diners adjust.',
  },
];
