/** Training Kitchen — grocery chains + local food source types */

export const GROCERY_CHAINS = [
  {
    id: 'walmart',
    name: 'Walmart',
    type: 'chain',
    tags: ['national', 'budget'],
    aisles: ['Produce', 'Meat', 'Dairy', 'Frozen', 'Pantry', 'Bakery'],
    tips: ['Great for staples and pantry basics', 'Check Great Value and Marketside for value', 'Use grocery pickup for meal-plan efficiency'],
    seasonal: 'Seasonal displays at front — holiday baking, summer grilling.',
  },
  {
    id: 'kroger',
    name: 'Kroger',
    type: 'chain',
    tags: ['national', 'regional'],
    aisles: ['Produce', 'Meat & Seafood', 'Deli', 'Dairy', 'Natural Foods'],
    tips: ['Digital coupons stack with sales', 'Simple Truth organic line', 'Boil-in-bag and meal kits in deli'],
    seasonal: 'Local produce tags in summer; floral near holidays.',
  },
  {
    id: 'costco',
    name: 'Costco',
    type: 'warehouse',
    tags: ['bulk', 'value'],
    aisles: ['Fresh', 'Meat', 'Dairy', 'Frozen', 'Dry Goods'],
    tips: ['Best for proteins and frozen veg in bulk', 'Kirkland Signature quality staples', 'Split large packs and freeze portions'],
    seasonal: 'Rotating seasonal items — berries, pies, holiday roasts.',
  },
  {
    id: 'target',
    name: 'Target',
    type: 'chain',
    tags: ['national', 'convenience'],
    aisles: ['Fresh', 'Frozen', 'Grocery', 'Household'],
    tips: ['Good for last-minute dinner fixes', 'Good & Gather house brand', 'Combine with household run'],
    seasonal: 'Seasonal endcaps — Super Bowl, back-to-school lunch.',
  },
  {
    id: 'whole_foods',
    name: 'Whole Foods Market',
    type: 'premium',
    tags: ['organic', 'premium'],
    aisles: ['Produce', 'Meat', 'Seafood', 'Dairy', 'Bulk', 'Prepared Foods'],
    tips: ['365 by Whole Foods for value organic', 'Butcher counter for custom cuts', 'Prime member deals on select items'],
    seasonal: 'Local farm tags on produce; holiday prime rib and turkeys.',
  },
  {
    id: 'trader_joes',
    name: "Trader Joe's",
    type: 'specialty',
    tags: ['unique', 'value'],
    aisles: ['Produce', 'Frozen', 'Dairy', 'Pantry'],
    tips: ['Unique frozen and sauce items', 'Small stores — quick shop', 'Fan favorites rotate — stock up when you see favorites'],
    seasonal: 'Fearless Flyer seasonal — pumpkin, peppermint, summer BBQ.',
  },
  {
    id: 'aldi',
    name: 'ALDI',
    type: 'discount',
    tags: ['budget', 'efficient'],
    aisles: ['Fresh', 'Meat', 'Dairy', 'Frozen', 'Pantry'],
    tips: ['Quarter deposit for cart — bring bags', 'Weekly Aldi Finds middle aisle', 'Excellent price on basics and cheese'],
    seasonal: 'Aldi Finds — German holiday treats, garden plants in spring.',
  },
  {
    id: 'publix',
    name: 'Publix',
    type: 'regional',
    tags: ['southeast', 'service'],
    aisles: ['Produce', 'Meat', 'Deli', 'Bakery', 'Seafood'],
    tips: ['BOGO sales on staples', 'Sub sandwiches while you shop', 'Aprons meal kits and recipes in store'],
    seasonal: 'Florida citrus and regional produce highlighted.',
  },
  {
    id: 'heb',
    name: 'H-E-B',
    type: 'regional',
    tags: ['texas', 'local'],
    aisles: ['Produce', 'Meat', 'Tex-Mex', 'Bakery', 'Prepared'],
    tips: ['Meal Simple ready-to-cook', 'Strong Tex-Mex and BBQ aisle', 'Central Market sister stores for gourmet'],
    seasonal: 'Texas-grown produce; Fiesta and holiday tamales.',
  },
  {
    id: 'safeway',
    name: 'Safeway / Albertsons',
    type: 'chain',
    tags: ['west', 'national'],
    aisles: ['Produce', 'Meat', 'Deli', 'Bakery'],
    tips: ['Just for U rewards', 'O Organics line', 'Combined with Vons, Jewel-Osco in some regions'],
    seasonal: 'Regional wine and cheese features.',
  },
  {
    id: 'wegmans',
    name: 'Wegmans',
    type: 'regional',
    tags: ['premium', 'experience'],
    aisles: ['Market Cafe', 'Produce', 'Meat', 'Cheese Shop', 'Bakery'],
    tips: ['Eat-in market cafe for inspiration', 'Extensive cheese and charcuterie', 'Meal kits near prepared foods'],
    seasonal: 'Local farm partnerships posted weekly.',
  },
  {
    id: 'sprouts',
    name: 'Sprouts Farmers Market',
    type: 'specialty',
    tags: ['produce', 'natural'],
    aisles: ['Produce', 'Bulk', 'Vitamins', 'Meat', 'Deli'],
    tips: ['Wednesday double ad day', 'Bulk bins for grains and nuts', 'Strong produce at competitive prices'],
    seasonal: 'Organic produce focus; holiday grazing boards.',
  },
];

export const LOCAL_FOOD_SOURCES = [
  {
    id: 'farmers_market',
    name: 'Farmers Market',
    type: 'local',
    pref: 'farmers_market',
    tags: ['seasonal', 'local'],
    tips: [
      'Arrive early for best selection — berries, greens, and eggs go fast.',
      'Ask growers what is peak this week and how they cook it.',
      'Bring cash and reusable bags; many vendors are small-batch.',
      'Plan meals around what you find rather than a fixed list.',
    ],
    shopping: 'Walk the market once before buying — compare price and quality. Buy heavy items last.',
  },
  {
    id: 'csa',
    name: 'CSA (Community Supported Agriculture)',
    type: 'local',
    pref: 'community_supported_ag',
    tags: ['seasonal', 'subscription'],
    tips: [
      'Weekly box teaches seasonal cooking — embrace surprise vegetables.',
      'Pick-up day is meal-plan day: sort what needs using first.',
      'Share or swap extras with neighbors if quantities are large.',
    ],
    shopping: 'Treat the box as your produce budget — supplement proteins at grocery.',
  },
  {
    id: 'local_butcher',
    name: 'Local Butcher',
    type: 'local',
    pref: 'local_butcher',
    tags: ['protein', 'craft'],
    tips: [
      'Ask for custom cuts and trimming — they know the animal.',
      'Bones and trim often cheap or free for stock.',
      'Many butchers dry-age or source local farms — ask provenance.',
    ],
    shopping: 'Call ahead for holiday roasts and special cuts.',
  },
  {
    id: 'local_dairy',
    name: 'Local Dairy & Creamery',
    type: 'local',
    pref: 'local_dairy',
    tags: ['dairy', 'regional'],
    tips: [
      'Fresh cheese and milk often beat supermarket on flavor.',
      'Farm stores may sell eggs and meat too.',
      'Check sell-by dates — local often shorter shelf life, better taste.',
    ],
    shopping: 'Combine with farmers market run when both are same-day.',
  },
  {
    id: 'seasonal_produce',
    name: 'Seasonal Produce Strategy',
    type: 'local',
    pref: 'seasonal_produce',
    tags: ['planning', 'savings'],
    tips: [
      'In-season produce costs less and tastes better.',
      'Freeze berries and corn at peak; can tomatoes in late summer.',
      'Use SousChef meal plans weighted to what is in season near you.',
    ],
    shopping: 'USDA seasonal charts + local extension office guides for your zone.',
  },
  {
    id: 'u_pick',
    name: 'U-Pick Farms & Orchards',
    type: 'local',
    tags: ['family', 'seasonal'],
    tips: [
      'Berries, apples, pumpkins — plan preserving same day.',
      'Check weather and field conditions before driving out.',
      'Great for kids to connect food to source.',
    ],
    shopping: 'Bring containers; wear boots; go early to beat heat.',
  },
  {
    id: 'fish_monger',
    name: 'Fish Monger & Seafood Counter',
    type: 'local',
    tags: ['seafood', 'fresh'],
    tips: [
      'Smell the counter — should smell like ocean, not ammonia.',
      'Ask what came in today vs. previously frozen.',
      'Whole fish often best value; ask to fillet.',
    ],
    shopping: 'Cook seafood within 24 hours of purchase.',
  },
  {
    id: 'food_coop',
    name: 'Food Co-op',
    type: 'local',
    tags: ['member', 'local'],
    tips: [
      'Member-owned — often spotlights local producers.',
      'Bulk section reduces packaging waste.',
      'Work-shift discounts at some co-ops.',
    ],
    shopping: 'Member day sales; local producer spotlight boards.',
  },
  {
    id: 'home_garden',
    name: 'Home Garden',
    type: 'local',
    pref: 'grow_garden',
    tags: ['grow', 'zero_mile'],
    tips: [
      'Herbs on the windowsill change daily cooking — start there.',
      'Plant what you eat most: tomatoes, peppers, greens.',
      'Harvest in morning for best texture; cook same day when possible.',
    ],
    shopping: 'Seed starting calendar for your zone; succession plant greens.',
  },
];
