/** Kitchen Academy — Master Baker career path */

import { mod, level } from './helpers.mjs';

export const TRACK_MASTER_BAKER = {
  id: 'track.master_baker',
  title: 'Master Baker',
  summary: 'Six-level baking path from first loaf to laminated pastry, chocolate work, and pastry leadership.',
  track_type: 'baking',
  featured: true,
  directory_id: 'directory.pastry_arts',
  degree_label: 'Diploma in Pastry Arts',
  levels: [
    level('level.baker_beginner', 1, 'Beginner Baker', 'Measure accurately, knead with confidence, and proof your first dough.', [
      mod('mod.baker_begin.measure_mix', 'Measure & Mix', 'Weight over volume — flour hydration starts with accurate scaling.', {
        techniques: ['technique.knife_skills'],
        flavors: ['flavor_profile.nutty', 'flavor_profile.sweet_savory'],
        ingredients: ['ingredient.flour.all_purpose', 'ingredient.sugar', 'ingredient.eggs'],
        spices: ['ingredient.salt', 'ingredient.cinnamon'],
        cultures: ['culture.american', 'culture.british'],
        practice_query: 'simple muffin or quick bread with proper measuring',
        teaching: ['Use a scale for flour — cups compress and ruin hydration.', 'Whisk dry ingredients together before wet for even distribution.', 'Read the recipe twice before preheating the oven.'],
      }),
      mod('mod.baker_begin.knead_proof', 'Knead & Proof', 'Develop gluten, then let yeast do the lifting.', {
        techniques: ['technique.knead', 'technique.proof'],
        flavors: ['flavor_profile.nutty'],
        ingredients: ['ingredient.flour.bread', 'ingredient.yeast', 'ingredient.water'],
        spices: ['ingredient.salt'],
        cultures: ['culture.french', 'culture.italian'],
        practice_query: 'basic yeasted dinner rolls',
        teaching: ['Windowpane test: stretch a small piece until translucent without tearing.', 'Proof until doubled — poke test should spring back slowly.', 'Salt controls yeast speed; never let salt touch yeast directly in dry mix.'],
      }),
      mod('mod.baker_begin.score_bake', 'Score & Bake Bread', 'Steam, score, and listen for the hollow thump of a finished loaf.', {
        techniques: ['technique.score_bread', 'technique.roast'],
        flavors: ['flavor_profile.umami', 'flavor_profile.nutty'],
        ingredients: ['ingredient.flour.bread', 'ingredient.water', 'ingredient.olive_oil'],
        spices: ['ingredient.salt', 'ingredient.seeds'],
        cultures: ['culture.french', 'culture.german'],
        practice_query: 'crusty artisan loaf with scored top',
        teaching: ['Score at a shallow angle with a lame or sharp knife — controls oven spring.', 'Steam in the first 10 minutes for crackling crust.', 'Internal temp 190–210°F for lean breads; thermometer beats color alone.'],
      }),
    ]),
    level('level.home_baker', 2, 'Home Baker', 'Cookies, cakes, and the chemistry of creaming and folding.', [
      mod('mod.home_baker.cream_butter', 'Creaming & Cookie Science', 'Room-temp butter, sugar crystals cutting air — the cookie foundation.', {
        techniques: ['technique.whip'],
        flavors: ['flavor_profile.sweet_savory', 'flavor_profile.nutty'],
        ingredients: ['ingredient.butter', 'ingredient.sugar', 'ingredient.flour.all_purpose'],
        spices: ['ingredient.salt', 'ingredient.vanilla'],
        cultures: ['culture.american'],
        practice_query: 'chewy chocolate chip cookies with creamed butter',
        teaching: ['Butter must be cool-room-temp — too soft and cookies spread flat.', 'Cream until pale and fluffy; sugar dissolves partially into butter.', 'Chill dough 30 minutes for thicker cookies with better flavor.'],
      }),
      mod('mod.home_baker.fold_gentle', 'Fold & Gentle Mix', 'Preserve air in batters — stop when streaks remain.', {
        techniques: ['technique.fold', 'technique.whip'],
        flavors: ['flavor_profile.floral_citrus', 'flavor_profile.rich_creamy'],
        ingredients: ['ingredient.eggs', 'ingredient.flour.all_purpose', 'ingredient.lemon'],
        spices: ['ingredient.salt'],
        cultures: ['culture.french', 'culture.british'],
        practice_query: 'genoise or chiffon cake with folded batter',
        teaching: ['Cut through center, scrape bottom, fold over — do not stir.', 'Fold dry into wet in thirds; deflating less is more.', 'Stop when a few flour streaks remain; over-mixing toughens cake.'],
      }),
      mod('mod.home_baker.blind_tart', 'Blind Bake Tart Shells', 'Par-bake pastry so fillings stay silky, not soggy.', {
        techniques: ['technique.blind_bake', 'technique.temper'],
        flavors: ['flavor_profile.rich_creamy', 'flavor_profile.bright_acid'],
        ingredients: ['ingredient.butter', 'ingredient.flour.all_purpose', 'ingredient.eggs'],
        spices: ['ingredient.salt', 'ingredient.vanilla'],
        cultures: ['culture.french'],
        practice_query: 'blind-baked tart shell for lemon curd',
        teaching: ['Dock the shell with a fork — steam escapes, fewer bubbles.', 'Line with parchment and pie weights; bake until edges golden.', 'Brush egg wash on hot shell to seal against wet fillings.'],
      }),
    ]),
    level('level.bread_baker', 3, 'Bread Baker', 'Enriched dough, fermentation timing, and sourdough thinking.', [
      mod('mod.bread.enrich_dough', 'Enriched Dough', 'Butter, eggs, and sugar change gluten and browning — brioche rules.', {
        techniques: ['technique.enrich_dough', 'technique.knead', 'technique.proof'],
        flavors: ['flavor_profile.rich_creamy', 'flavor_profile.sweet_savory'],
        ingredients: ['ingredient.butter', 'ingredient.eggs', 'ingredient.flour.bread'],
        spices: ['ingredient.salt', 'ingredient.sugar'],
        cultures: ['culture.french', 'culture.japanese'],
        practice_query: 'brioche buns or challah braid',
        teaching: ['Add butter in stages after gluten develops — fat inhibits early kneading.', 'Enriched dough proofs slower; watch volume, not the clock.', 'Egg wash gives shine; milk wash gives soft brown crust.'],
      }),
      mod('mod.bread.laminate', 'Laminate & Croissant', 'Butter block, letter folds, and the science of flaky layers.', {
        techniques: ['technique.laminate', 'technique.proof'],
        flavors: ['flavor_profile.rich_creamy', 'flavor_profile.nutty'],
        ingredients: ['ingredient.butter', 'ingredient.flour.all_purpose', 'ingredient.yeast'],
        spices: ['ingredient.salt'],
        cultures: ['culture.french'],
        practice_query: 'croissants or rough puff pastry',
        teaching: ['Butter and dough must be same consistency — cold but pliable.', 'Rest between folds; gluten relaxes, butter stays in layers.', 'Proof laminated dough until jiggly — under-proofed layers stay dense.'],
      }),
      mod('mod.bread.ferment_depth', 'Long Ferment & Flavor', 'Overnight retards and preferments for complex bread flavor.', {
        techniques: ['technique.ferment', 'technique.proof'],
        flavors: ['flavor_profile.fermented_depth', 'flavor_profile.tangy'],
        ingredients: ['ingredient.flour.bread', 'ingredient.sourdough_starter', 'ingredient.water'],
        spices: ['ingredient.salt'],
        cultures: ['culture.french', 'culture.german'],
        practice_query: 'overnight retarded country loaf',
        teaching: ['Cold retard slows yeast, develops acid and aroma.', 'Starter must be active — floats in water at peak.', 'Score deeper on high-hydration doughs for controlled expansion.'],
      }),
    ]),
    level('level.pastry_cook', 4, 'Pastry Cook', 'Chocolate, custards, and precision on the pastry station.', [
      mod('mod.pastry_cook.temper_choc', 'Temper Chocolate', 'Crystal structure for snap, shine, and stable decorations.', {
        techniques: ['technique.temper_chocolate'],
        flavors: ['flavor_profile.sweet_savory', 'flavor_profile.bitter_bright'],
        ingredients: ['ingredient.dark_chocolate', 'ingredient.cocoa_butter'],
        spices: ['ingredient.sea_salt'],
        cultures: ['culture.french', 'culture.belgian'],
        practice_query: 'tempered chocolate bark or dipped strawberries',
        teaching: ['Seed method: melt 2/3 chocolate, stir in remaining finely chopped.', 'Work at 88–90°F for dark chocolate; thermometer is mandatory.', 'Test on parchment — sets glossy in 3 minutes or retemper.'],
      }),
      mod('mod.pastry_cook.custard_set', 'Custards & Setting', 'Temper eggs into hot dairy — silky crème without scramble.', {
        techniques: ['technique.temper', 'technique.roast'],
        flavors: ['flavor_profile.rich_creamy', 'flavor_profile.floral_citrus'],
        ingredients: ['ingredient.eggs', 'ingredient.cream', 'ingredient.vanilla'],
        spices: ['ingredient.salt', 'ingredient.nutmeg'],
        cultures: ['culture.french'],
        practice_query: 'crème brûlée or pastry cream',
        teaching: ['Temper by ladling hot cream into eggs slowly while whisking.', 'Strain custards through fine mesh — silky texture, no chalazae.', 'Bake in water bath; edges set, center still wobbles slightly.'],
      }),
      mod('mod.pastry_cook.macaron', 'Macaronage & Meringue', 'Fold almond batter to ribbon stage — feet come from technique.', {
        techniques: ['technique.macaronage', 'technique.whip', 'technique.piping'],
        flavors: ['flavor_profile.sweet_savory', 'flavor_profile.floral_citrus'],
        ingredients: ['ingredient.almond_flour', 'ingredient.sugar', 'ingredient.eggs'],
        spices: ['ingredient.vanilla'],
        cultures: ['culture.french'],
        practice_query: 'French macarons with ganache filling',
        teaching: ['Macaronage: fold until batter ribbons off spatula like lava.', 'Rest piped shells until skin forms — touch without sticking.', 'Low oven, steady temp; open door cracks shells from shock.'],
      }),
    ]),
    level('level.pastry_chef', 5, 'Pastry Chef', 'Sugar work, plated desserts, and pastry menu architecture.', [
      mod('mod.pastry_chef.sugar_work', 'Sugar Work & Caramel', 'Cook sugar to thread, soft ball, and hard crack with safety.', {
        techniques: ['technique.sugar_work'],
        flavors: ['flavor_profile.sweet_savory', 'flavor_profile.bitter_bright'],
        ingredients: ['ingredient.sugar', 'ingredient.glucose', 'ingredient.cream'],
        spices: ['ingredient.sea_salt'],
        cultures: ['culture.french'],
        practice_query: 'salted caramel sauce or spun sugar garnish',
        teaching: ['Clean pot sides with wet brush — sugar crystals seed premature crystallization.', 'Caramel goes from perfect to bitter in seconds; cold bath stops carryover.', 'Never touch hot sugar; water bowl nearby for burns.'],
      }),
      mod('mod.pastry_chef.piping_finish', 'Piping & Finish Work', 'Consistent pressure, temperature, and garnish discipline.', {
        techniques: ['technique.piping', 'technique.whip'],
        flavors: ['flavor_profile.rich_creamy', 'flavor_profile.floral_citrus'],
        ingredients: ['ingredient.butter', 'ingredient.cream_cheese', 'ingredient.powdered_sugar'],
        spices: ['ingredient.vanilla'],
        cultures: ['culture.french', 'culture.american'],
        practice_query: 'decorated layer cake with piped buttercream',
        teaching: ['Buttercream at 68°F pipes clean — too warm slumps, too cold tears.', 'Practice on parchment before committing to the cake.', 'Garnish should echo flavors inside — citrus zest on lemon cake, not random mint.'],
      }),
      mod('mod.pastry_chef.plated_dessert', 'Plated Dessert Architecture', 'Temperature contrast, sauce placement, and the three-bite rule.', {
        techniques: ['technique.fold', 'technique.temper_chocolate'],
        flavors: ['flavor_profile.bitter_bright', 'flavor_profile.sweet_savory'],
        ingredients: ['ingredient.dark_chocolate', 'ingredient.berries', 'ingredient.cream'],
        spices: ['ingredient.mint'],
        cultures: ['culture.french', 'culture.japanese'],
        practice_query: 'plated dessert with sauce, crunch, and temperature contrast',
        teaching: ['Build bottom to top: sauce, crunch, mousse, garnish.', 'Odd numbers on the plate look intentional — threes and fives.', 'Cold plate for chilled desserts; warm sauce only if designed to flow.'],
      }),
    ]),
    level('level.master_baker', 6, 'Master Baker', 'Production scale, recipe R&D, and mentoring the pastry brigade.', [
      mod('mod.master.production_scale', 'Production & Scaling', 'Batch formulas, fermentation schedules, and oven loading strategy.', {
        techniques: ['technique.knead', 'technique.proof', 'technique.score_bread'],
        flavors: ['flavor_profile.nutty', 'flavor_profile.umami'],
        ingredients: ['ingredient.flour.bread', 'ingredient.yeast', 'ingredient.water'],
        spices: ['ingredient.salt', 'ingredient.seeds'],
        cultures: ['culture.french', 'culture.german'],
        practice_query: 'scale bread recipe from 4 to 40 loaves with baker\'s percentages',
        teaching: ['Baker\'s percentages: flour is always 100%, everything else relative.', 'Stagger oven loads for consistent bake — know your hot spots.', 'Document floor time and dough temp; seasons change fermentation.'],
      }),
      mod('mod.master.recipe_rd', 'Recipe R&D & Documentation', 'Test, version, and hand off formulas the brigade can repeat.', {
        techniques: ['technique.laminate', 'technique.enrich_dough'],
        flavors: ['flavor_profile.fermented_depth', 'flavor_profile.sweet_savory'],
        ingredients: ['ingredient.flour.all_purpose', 'ingredient.butter', 'ingredient.sourdough_starter'],
        spices: ['ingredient.salt'],
        cultures: ['culture.french', 'culture.american'],
        practice_query: 'develop and document signature house viennoiserie',
        teaching: ['Change one variable per test batch — fat %, hydration, fold count.', 'Photo each stage for training cards, not just the finished item.', 'Version numbers on recipes; never overwrite without saving the prior winner.'],
      }),
      mod('mod.master.mentor_brigade', 'Mentor & Quality Control', 'Taste panels, waste tracking, and building the next pastry lead.', {
        techniques: ['technique.blind_bake', 'technique.temper_chocolate'],
        flavors: ['flavor_profile.rich_creamy'],
        ingredients: ['ingredient.chocolate', 'ingredient.cream', 'ingredient.fruit'],
        spices: ['ingredient.salt'],
        cultures: ['culture.french', 'culture.global'],
        practice_query: 'pastry quality audit with scoring rubric for brigade',
        teaching: ['Daily taste panel: one item from each station, scored blind.', 'Track scrap and rework — quality and margin live in the same spreadsheet.', 'Promote on teaching ability, not just technical skill.'],
      }),
    ]),
  ],
};
