/** Kitchen Academy — World Cuisines Diploma */

import { mod, level } from './helpers.mjs';

export const TRACK_GLOBAL_CUISINES = {
  id: 'track.global_cuisines',
  title: 'World Cuisines Diploma',
  summary: 'Six-level regional diploma — Asia, Mediterranean, Latin America, Middle East, Africa, and a fusion capstone with pantry-matched practice per culture.',
  track_type: 'diploma',
  featured: true,
  directory_id: 'directory.world_studies',
  degree_label: 'World Cuisines Diploma',
  levels: [
    level('level.world.asia', 1, 'East & Southeast Asia', 'Wok hei, rice noodles, and the soy-ginger-garlic trinity.', [
      mod('mod.world.stir_fry', 'Stir Fry & Wok Logic', 'Heat, motion, and mise en place for Asian quick cooking.', {
        techniques: ['technique.stir_fry', 'technique.steam'],
        flavors: ['flavor_profile.umami', 'flavor_profile.spicy_heat'],
        ingredients: ['ingredient.rice', 'ingredient.soy_sauce', 'ingredient.ginger'],
        spices: ['ingredient.garlic', 'ingredient.sesame_oil'],
        cultures: ['culture.chinese', 'culture.thai'],
        practice_query: 'stir fried noodles with vegetables',
        teaching: ['Protein out, veg by cook time, sauce last.', 'Sesame oil finishes — never fry in it alone.', 'Day-old rice fries better than fresh.'],
      }),
      mod('mod.world.broth_asia', 'Broths & Bowls', 'Ramen, pho, and congee foundations.', {
        techniques: ['technique.simmer', 'technique.simmer'],
        flavors: ['flavor_profile.umami'],
        ingredients: ['ingredient.chicken_stock', 'ingredient.rice', 'ingredient.ginger'],
        cultures: ['culture.japanese', 'culture.vietnamese'],
        practice_query: 'simple pho or miso soup bowl',
        teaching: ['Skim stock for clarity — patience builds clean broth.', 'Miso off the boil — live cultures die in rolling water.', 'Bowl toppings prepped before broth is ready.'],
      }),
      mod('mod.world.curry_asia', 'Curry Pastes & Coconut', 'Thai and Malaysian curry building blocks.', {
        techniques: ['technique.saute', 'technique.simmer'],
        flavors: ['flavor_profile.spicy_heat', 'flavor_profile.rich_creamy'],
        ingredients: ['ingredient.coconut_milk', 'ingredient.chicken', 'ingredient.basil'],
        spices: ['ingredient.curry_paste', 'ingredient.fish_sauce'],
        cultures: ['culture.thai', 'culture.malaysian'],
        practice_query: 'coconut curry with jasmine rice',
        teaching: ['Fry paste in oil until fragrant before liquid.', 'Fish sauce replaces salt — add gradually.', 'Fresh herbs at the very end.'],
      }),
    ]),
    level('level.world.med', 2, 'Mediterranean & Europe', 'Olive oil, acid, and herb-driven plates.', [
      mod('mod.world.med_roast', 'Roast & Herb Mediterranean', 'Sheet pan Greek and Italian weeknight logic.', {
        techniques: ['technique.roast', 'technique.layer_season'],
        flavors: ['flavor_profile.herbaceous', 'flavor_profile.bright_acid'],
        ingredients: ['ingredient.chicken', 'ingredient.olive_oil', 'ingredient.lemon'],
        spices: ['ingredient.oregano', 'ingredient.garlic'],
        cultures: ['culture.greek', 'culture.italian'],
        practice_query: 'mediterranean roasted chicken and vegetables',
        teaching: ['Olive oil carries herb flavor — do not dry roast.', 'Lemon after heat preserves acid.', 'Feta and olives finish, not cook.'],
      }),
      mod('mod.world.pasta', 'Pasta & Sauce Pairing', 'Al dente timing and sauce cling physics.', {
        techniques: ['technique.boil', 'technique.saute'],
        flavors: ['flavor_profile.umami', 'flavor_profile.rich_creamy'],
        ingredients: ['ingredient.pasta', 'ingredient.tomato', 'ingredient.parmesan'],
        spices: ['ingredient.basil', 'ingredient.garlic'],
        cultures: ['culture.italian'],
        practice_query: 'pasta with tomato basil sauce',
        teaching: ['Salt pasta water aggressively.', 'Finish pasta in the sauce with pasta water — emulsion clings.', 'Cheese off heat for smooth melt.'],
      }),
      mod('mod.world.tapas', 'Tapas & Small Plates', 'Spanish sharing portions and bold simple flavors.', {
        techniques: ['technique.saute', 'technique.roast'],
        flavors: ['flavor_profile.smoky', 'flavor_profile.bright_acid'],
        ingredients: ['ingredient.potato', 'ingredient.olive_oil', 'ingredient.paprika'],
        spices: ['ingredient.salt', 'ingredient.smoked_paprika'],
        cultures: ['culture.spanish'],
        practice_query: 'patatas bravas or garlic shrimp tapas',
        teaching: ['Small plates need big seasoning — bites are tiny.', 'Smoked paprika is Spanish shorthand for depth.', 'Serve at peak crispness — tapas wait for no one.'],
      }),
    ]),
    level('level.world.latin', 3, 'Latin America & Caribbean', 'Sofrito, masa, and bright acid finishes.', [
      mod('mod.world.sofrito', 'Sofrito & Achiote Bases', 'Latin flavor starts before protein hits the pan.', {
        techniques: ['technique.saute', 'technique.mirepoix'],
        flavors: ['flavor_profile.umami', 'flavor_profile.spicy_heat'],
        ingredients: ['ingredient.onion', 'ingredient.pepper', 'ingredient.tomato'],
        spices: ['ingredient.cumin', 'ingredient.achiote'],
        cultures: ['culture.mexican', 'culture.cuban'],
        practice_query: 'rice and beans with sofrito base',
        teaching: ['Cook sofrito until paste darkens — color = flavor.', 'Cilantro stems in cook, leaves at finish.', 'Acid from lime is mandatory, not optional.'],
      }),
      mod('mod.world.taco', 'Tacos & Tortilla Service', 'Warm tortillas, balanced fillings, salsa verde/roja.', {
        techniques: ['technique.grill', 'technique.saute'],
        flavors: ['flavor_profile.spicy_heat', 'flavor_profile.fresh_light'],
        ingredients: ['ingredient.beef', 'ingredient.tortilla', 'ingredient.onion'],
        spices: ['ingredient.chili_powder', 'ingredient.cilantro'],
        cultures: ['culture.mexican', 'culture.tex_mex'],
        practice_query: 'street style tacos with salsa',
        teaching: ['Double-stack corn tortillas for structure.', 'Char salsa ingredients for depth.', 'Onion-cilantro-lime finish is the holy trinity.'],
      }),
      mod('mod.world.caribbean', 'Caribbean Spice & Smoke', 'Jerk, coconut rice, and tropical heat balance.', {
        techniques: ['technique.grill', 'technique.slow_cook'],
        flavors: ['flavor_profile.spicy_heat', 'flavor_profile.smoky'],
        ingredients: ['ingredient.chicken', 'ingredient.coconut_milk', 'ingredient.lime'],
        spices: ['ingredient.allspice', 'ingredient.scotch_bonnet'],
        cultures: ['culture.caribbean', 'culture.jamaican'],
        practice_query: 'jerk seasoned grilled chicken',
        teaching: ['Jerk needs time in marinade — overnight ideal.', 'Scotch bonnet heat blooms with allspice and thyme.', 'Sweet plantain cools fiery plates.'],
      }),
    ]),
    level('level.world.mideast', 4, 'Middle East & North Africa', 'Spice toasting, grains, and yogurt sauces.', [
      mod('mod.world.spice_toast', 'Spice Toasting & Blends', 'Baharat, ras el hanout, and zaatar logic.', {
        techniques: ['technique.saute', 'technique.roast'],
        flavors: ['flavor_profile.earthy', 'flavor_profile.spicy_heat'],
        ingredients: ['ingredient.rice', 'ingredient.chickpeas', 'ingredient.yogurt'],
        spices: ['ingredient.cumin', 'ingredient.coriander', 'ingredient.sumac'],
        cultures: ['culture.middle_eastern', 'culture.moroccan'],
        practice_query: 'spiced rice pilaf with toasted nuts',
        teaching: ['Toast whole spices before grinding.', 'Sumac is acid — use where you would lemon.', 'Yogurt sauce cools and carries spice.'],
      }),
      mod('mod.world.mezze', 'Mezze & Flatbread', 'Hummus, falafel, and shared Middle Eastern plates.', {
        techniques: ['technique.puree', 'technique.fry'],
        flavors: ['flavor_profile.umami', 'flavor_profile.bright_acid'],
        ingredients: ['ingredient.chickpeas', 'ingredient.tahini', 'ingredient.lemon'],
        spices: ['ingredient.cumin', 'ingredient.garlic'],
        cultures: ['culture.lebanese', 'culture.turkish'],
        practice_query: 'hummus and warm pita platter',
        teaching: ['Silky hummus needs cold water while blending.', 'Falafel needs dried chickpeas soaked — canned fails.', 'Olive oil pool on hummus is presentation and flavor.'],
      }),
      mod('mod.world.tagine', 'Tagine & Slow Braise', 'Moroccan low moist heat and dried fruit balance.', {
        techniques: ['technique.braise', 'technique.slow_cook'],
        flavors: ['flavor_profile.sweet_savory', 'flavor_profile.spicy_heat'],
        ingredients: ['ingredient.lamb', 'ingredient.apricots', 'ingredient.onion'],
        spices: ['ingredient.cinnamon', 'ingredient.ginger'],
        cultures: ['culture.moroccan'],
        practice_query: 'moroccan spiced chicken tagine',
        teaching: ['Sweet-dry fruit against savory spice is the tagine signature.', 'Low lid moisture — check liquid rarely.', 'Couscous steams off tagine steam when possible.'],
      }),
    ]),
    level('level.world.africa', 5, 'Sub-Saharan Africa', 'Berbere, injera logic, and communal starch scoops.', [
      mod('mod.world.berbere', 'Berbere & Stews', 'Ethiopian spice depth and long simmer.', {
        techniques: ['technique.simmer', 'technique.saute'],
        flavors: ['flavor_profile.spicy_heat', 'flavor_profile.earthy'],
        ingredients: ['ingredient.lentils', 'ingredient.onion', 'ingredient.tomato'],
        spices: ['ingredient.berbere', 'ingredient.ginger'],
        cultures: ['culture.ethiopian'],
        practice_query: 'spiced lentil stew with berbere',
        teaching: ['Berbere in hot oil first — never raw in water.', 'Injera sponges stew — plan starch alongside.', 'Communal platter teaches portion sharing.'],
      }),
      mod('mod.world.west_africa', 'West African Peanut & Tomato', 'Nigerian and Ghanaian one-pot richness.', {
        techniques: ['technique.simmer', 'technique.stir_fry'],
        flavors: ['flavor_profile.rich_creamy', 'flavor_profile.umami'],
        ingredients: ['ingredient.peanut_butter', 'ingredient.tomato', 'ingredient.rice'],
        spices: ['ingredient.scotch_bonnet', 'ingredient.ginger'],
        cultures: ['culture.nigerian'],
        practice_query: 'peanut stew with rice',
        teaching: ['Peanut butter splits if boiled hard — simmer gently.', 'Scotch bonnet whole adds flavor without full heat if removed early.', 'Tomato paste fried in oil is West African sofrito.'],
      }),
      mod('mod.world.south_africa', 'South African Braai & Chakalaka', 'Grill culture and spicy relish sides.', {
        techniques: ['technique.grill', 'technique.saute'],
        flavors: ['flavor_profile.smoky', 'flavor_profile.spicy_heat'],
        ingredients: ['ingredient.beef', 'ingredient.beans', 'ingredient.pepper'],
        spices: ['ingredient.curry_powder', 'ingredient.chili'],
        cultures: ['culture.south_african'],
        practice_query: 'grilled meat with spicy vegetable relish',
        teaching: ['Braai is social — proteins rest while sides finish.', 'Chakalaka needs char on peppers first.', 'Maize pap holds sauce like mashed potato holds gravy.'],
      }),
    ]),
    level('level.world.fusion', 6, 'Fusion Capstone', 'Respectful fusion — technique transfer without cultural erasure.', [
      mod('mod.world.fusion_map', 'Flavor Mapping Across Cultures', 'Identify shared pillars: acid, fat, heat, aromatics.', {
        techniques: ['technique.plan_menu'],
        flavors: ['flavor_profile.umami', 'flavor_profile.bright_acid'],
        ingredients: ['ingredient.lime', 'ingredient.soy_sauce', 'ingredient.olive_oil'],
        cultures: ['culture.asian', 'culture.mediterranean'],
        practice_query: 'fusion bowl combining two cuisine profiles',
        teaching: ['Fusion works when techniques align, not when random ingredients collide.', 'Name inspirations honestly — credit is part of craft.', 'One anchor cuisine, one accent — not fifty-fifty chaos.'],
      }),
      mod('mod.world.pantry_fusion', 'Pantry-Driven World Menu', 'Build a world menu from what you actually have.', {
        techniques: ['technique.substitute', 'technique.plan_menu'],
        flavors: ['flavor_profile.fresh_light'],
        ingredients: ['ingredient.rice', 'ingredient.beans', 'ingredient.onion'],
        cultures: ['culture.asian', 'culture.latin', 'culture.middle_eastern'],
        practice_query: 'international weeknight menu from pantry staples',
        teaching: ['Clara match_dishes filters 568k recipes by cuisine tag.', 'Substitute with graph logic — same role, different ingredient.', 'Three cuisines, one shopping list — overlap is your friend.'],
      }),
      mod('mod.world.capstone', 'Capstone: World Passport Tasting', 'Six small plates, six regions, one coherent menu — diploma exam.', {
        techniques: ['technique.stir_fry', 'technique.roast', 'technique.simmer'],
        flavors: ['flavor_profile.umami', 'flavor_profile.spicy_heat', 'flavor_profile.bright_acid'],
        ingredients: ['ingredient.chicken', 'ingredient.rice', 'ingredient.spices'],
        cultures: ['culture.chinese', 'culture.mexican', 'culture.moroccan', 'culture.indian'],
        practice_query: 'world cuisine tasting menu small plates',
        time_limit_minutes: 150,
        judge_criteria: ['Regional authenticity', 'Menu coherence', 'Technique range', 'Pantry efficiency'],
        teaching: ['Prep by region station — mis en place prevents crossover confusion.', 'Label each plate with region and key technique.', 'Passport complete when guest can name the flavor pillar per bite.'],
      }),
    ]),
  ],
};
