/** AUTO-GENERATED by scripts/build-marketing-stats.mjs — do not edit manually */
export const CORPUS_STATS = {
  generatedAt: '2026-06-09T15:38:42.866Z',
  recipeTotal: 284255,
  recipeCountFormatted: '284,000+',
  recipeCountCompact: '284K+',
  recipeCountExact: '284,255',
  cuisines: 48,
  courses: 10,
  techniques: 53,
  deepDives: 161,
  flavorProfiles: 18,
  foodSources: 21,
} as const;
