/** AUTO-GENERATED by scripts/build-marketing-stats.mjs — do not edit manually */
export const CORPUS_STATS = {
  generatedAt: '2026-06-10T00:57:06.889Z',
  recipeTotal: 568510,
  recipeCountFormatted: '568,000+',
  recipeCountCompact: '568K+',
  recipeCountExact: '568,510',
  cuisines: 48,
  courses: 10,
  techniques: 53,
  deepDives: 161,
  flavorProfiles: 18,
  foodSources: 21,
} as const;
