/** 48 world cuisines for corpus v2 */
export const CUISINES = [
  { key: 'italian', id: 'cuisine.italian', label: 'Italian', region: 'europe', spice: 'garlic and basil', starch: 'pasta', fat: 'olive oil' },
  { key: 'french', id: 'cuisine.french', label: 'French', region: 'europe', spice: 'herbes de Provence', starch: 'potatoes', fat: 'butter' },
  { key: 'greek', id: 'cuisine.greek', label: 'Greek', region: 'mediterranean', spice: 'oregano and lemon', starch: 'rice', fat: 'olive oil' },
  { key: 'spanish', id: 'cuisine.spanish', label: 'Spanish', region: 'europe', spice: 'smoked paprika', starch: 'rice', fat: 'olive oil' },
  { key: 'german', id: 'cuisine.german', label: 'German', region: 'europe', spice: 'caraway', starch: 'potatoes', fat: 'butter' },
  { key: 'british', id: 'cuisine.british', label: 'British', region: 'europe', spice: 'thyme', starch: 'potatoes', fat: 'butter' },
  { key: 'irish', id: 'cuisine.irish', label: 'Irish', region: 'europe', spice: 'parsley', starch: 'potatoes', fat: 'butter' },
  { key: 'polish', id: 'cuisine.polish', label: 'Polish', region: 'europe', spice: 'dill', starch: 'potatoes', fat: 'sour cream' },
  { key: 'hungarian', id: 'cuisine.hungarian', label: 'Hungarian', region: 'europe', spice: 'paprika', starch: 'noodles', fat: 'sour cream' },
  { key: 'scandinavian', id: 'cuisine.scandinavian', label: 'Scandinavian', region: 'europe', spice: 'dill', starch: 'potatoes', fat: 'butter' },
  { key: 'portuguese', id: 'cuisine.portuguese', label: 'Portuguese', region: 'europe', spice: 'piri piri', starch: 'rice', fat: 'olive oil' },
  { key: 'russian', id: 'cuisine.russian', label: 'Russian', region: 'europe', spice: 'dill and sour cream', starch: 'potatoes', fat: 'butter' },
  { key: 'mediterranean', id: 'cuisine.mediterranean', label: 'Mediterranean', region: 'mediterranean', spice: 'oregano', starch: 'couscous', fat: 'olive oil' },
  { key: 'lebanese', id: 'cuisine.lebanese', label: 'Lebanese', region: 'middle_east', spice: 'sumac and zaatar', starch: 'pita', fat: 'olive oil' },
  { key: 'turkish', id: 'cuisine.turkish', label: 'Turkish', region: 'middle_east', spice: 'cumin and mint', starch: 'bulgur', fat: 'olive oil' },
  { key: 'moroccan', id: 'cuisine.moroccan', label: 'Moroccan', region: 'africa', spice: 'ras el hanout', starch: 'couscous', fat: 'olive oil' },
  { key: 'persian', id: 'cuisine.persian', label: 'Persian', region: 'middle_east', spice: 'saffron and turmeric', starch: 'rice', fat: 'yogurt' },
  { key: 'middle_eastern', id: 'cuisine.middle_eastern', label: 'Middle Eastern', region: 'middle_east', spice: 'baharat', starch: 'rice', fat: 'tahini' },
  { key: 'mexican', id: 'cuisine.mexican', label: 'Mexican', region: 'latin', spice: 'cumin and chili', starch: 'corn tortillas', fat: 'lard or oil' },
  { key: 'tex_mex', id: 'cuisine.tex_mex', label: 'Tex-Mex', region: 'american', spice: 'chili powder', starch: 'flour tortillas', fat: 'cheese' },
  { key: 'cuban', id: 'cuisine.cuban', label: 'Cuban', region: 'latin', spice: 'citrus and garlic', starch: 'rice', fat: 'olive oil' },
  { key: 'brazilian', id: 'cuisine.brazilian', label: 'Brazilian', region: 'latin', spice: 'lime and garlic', starch: 'rice', fat: 'oil' },
  { key: 'peruvian', id: 'cuisine.peruvian', label: 'Peruvian', region: 'latin', spice: 'aji amarillo', starch: 'potatoes', fat: 'olive oil' },
  { key: 'colombian', id: 'cuisine.colombian', label: 'Colombian', region: 'latin', spice: 'cumin', starch: 'rice', fat: 'oil' },
  { key: 'argentinian', id: 'cuisine.argentinian', label: 'Argentinian', region: 'latin', spice: 'chimichurri', starch: 'potatoes', fat: 'olive oil' },
  { key: 'caribbean', id: 'cuisine.caribbean', label: 'Caribbean', region: 'latin', spice: 'jerk seasoning', starch: 'rice and peas', fat: 'coconut oil' },
  { key: 'chinese', id: 'cuisine.chinese', label: 'Chinese', region: 'asia', spice: 'ginger and soy', starch: 'rice', fat: 'sesame oil' },
  { key: 'japanese', id: 'cuisine.japanese', label: 'Japanese', region: 'asia', spice: 'miso and ginger', starch: 'rice', fat: 'sesame oil' },
  { key: 'korean', id: 'cuisine.korean', label: 'Korean', region: 'asia', spice: 'gochujang', starch: 'rice', fat: 'sesame oil' },
  { key: 'thai', id: 'cuisine.thai', label: 'Thai', region: 'asia', spice: 'lemongrass and basil', starch: 'rice noodles', fat: 'coconut milk' },
  { key: 'vietnamese', id: 'cuisine.vietnamese', label: 'Vietnamese', region: 'asia', spice: 'fish sauce and lime', starch: 'rice noodles', fat: 'oil' },
  { key: 'indian', id: 'cuisine.indian', label: 'Indian', region: 'asia', spice: 'garam masala', starch: 'basmati rice', fat: 'ghee' },
  { key: 'filipino', id: 'cuisine.filipino', label: 'Filipino', region: 'asia', spice: 'garlic and vinegar', starch: 'rice', fat: 'oil' },
  { key: 'indonesian', id: 'cuisine.indonesian', label: 'Indonesian', region: 'asia', spice: 'turmeric and galangal', starch: 'rice', fat: 'coconut oil' },
  { key: 'malaysian', id: 'cuisine.malaysian', label: 'Malaysian', region: 'asia', spice: 'curry paste', starch: 'rice', fat: 'coconut milk' },
  { key: 'asian', id: 'cuisine.asian', label: 'Pan-Asian', region: 'asia', spice: 'soy and ginger', starch: 'rice', fat: 'sesame oil' },
  { key: 'ethiopian', id: 'cuisine.ethiopian', label: 'Ethiopian', region: 'africa', spice: 'berbere', starch: 'injera', fat: 'niter kibbeh' },
  { key: 'nigerian', id: 'cuisine.nigerian', label: 'Nigerian', region: 'africa', spice: 'scotch bonnet', starch: 'rice', fat: 'palm oil' },
  { key: 'south_african', id: 'cuisine.south_african', label: 'South African', region: 'africa', spice: 'curry powder', starch: 'pap', fat: 'oil' },
  { key: 'southern', id: 'cuisine.southern', label: 'Southern US', region: 'american', spice: 'black pepper', starch: 'cornbread', fat: 'butter' },
  { key: 'soul_food', id: 'cuisine.soul_food', label: 'Soul Food', region: 'american', spice: 'cayenne', starch: 'rice', fat: 'butter' },
  { key: 'cajun', id: 'cuisine.cajun', label: 'Cajun & Creole', region: 'american', spice: 'Cajun seasoning', starch: 'rice', fat: 'butter' },
  { key: 'comfort', id: 'cuisine.comfort', label: 'American Comfort', region: 'american', spice: 'garlic powder', starch: 'potatoes', fat: 'butter' },
  { key: 'bbq', id: 'cuisine.bbq', label: 'BBQ & Smokehouse', region: 'american', spice: 'smoked paprika', starch: 'buns', fat: 'BBQ sauce' },
  { key: 'hawaiian', id: 'cuisine.hawaiian', label: 'Hawaiian', region: 'pacific', spice: 'ginger', starch: 'rice', fat: 'coconut' },
  { key: 'american', id: 'cuisine.american', label: 'Classic American', region: 'american', spice: 'salt and pepper', starch: 'potatoes', fat: 'butter' },
  { key: 'vegetarian', id: 'cuisine.vegetarian', label: 'Vegetarian', region: 'global', spice: 'herbs', starch: 'grains', fat: 'olive oil' },
  { key: 'vegan', id: 'cuisine.vegan', label: 'Vegan', region: 'global', spice: 'nutritional yeast', starch: 'legumes', fat: 'olive oil' },
];
